<div id="fundo-externo">
    <div id="fundo"></div>
</div>
<div class="container">    
    <div class="row">
        <div class="col-lg-12">
            <a href="<?php echo $this->url(array('controller' => 'index')); ?>">
                <img src="<?php echo $this->baseUrl('views/img/logo.png'); ?>" class="img img-responsive"/>
            </a>
        </div>
    </div>     
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <div class="site">
                <h3>Contato</h3><hr />
                <?php echo $this->form; ?>
                <p class="small">* Campos obrigatórios</p>
            </div>
        </div>
    </div>   
</div>