        <hr style="border-color: #3e8f3e" />
        <p style="font-weight: bold">
            Socexx.com - Sua rede social do futebol!
        </p>
        <p>
            <a href="socexx.com" style="color: #3e8f3e">socexx.com</a>
        </p>
        <p style="font-size: 10px;">
            <span>E-mail enviado automaticamente. Por favor não responda.</span>
        </p>
   </td>
  </tr>
</table>
</body>
