<!-- BOTAO DE POST -->
<div class="row">
    <div class="col-lg-12">
        <a href="" class="btn btn-primary" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> Postar</a>
        <hr />
    </div>
</div>
<!-- POSTS -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading bolder">avatar - nome</div>
            <div class="panel-body">
                content
            </div>
        </div>        
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading bolder">avatar - nome</div>
            <div class="panel-body">
                content
            </div>
        </div>        
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                Cornete - Comente - Zoe
            </div>
            <div class="modal-body">
                <?php echo $this->formPost; ?>
            </div>
        </div>
    </div>
</div>