<!-- BOTAO DE POST -->
<div class="row">
    <div class="col-lg-12 text-right">
        <a href="" class="btn btn-success" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> NOVO POST</a>
        <hr />
    </div>
</div>
<!-- POSTS -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-info">
            <div class="panel-heading bolder">TITLE</div>
            <div class="panel-body">
                CONTENT POST
            </div>
            <div class="panel-footer text-right">
                <a href="" class="text-success interactions">
                    <span class="badge">5</span>
                    <i class="fa fa-thumbs-o-up fa-2x"></i>
                </a>
                <a href="" class="text-danger interactions">
                    <span class="badge">5</span>
                    <i class="fa fa-thumbs-o-down fa-2x"></i>
                </a>
                <a href="" class="text-info interactions">
                    <span class="badge">5</span>
                    <i class="fa fa-comments fa-2x"></i>
                </a>
                <a href="" class="text-primary interactions">
                    <span class="badge">5</span>
                    <i class="fa fa-share fa-2x"></i>
                </a>
            </div>
        </div>        
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Novo Post</h4>
            </div>
            <div class="modal-body">
                <?php echo $this->formPost; ?>
            </div>
        </div>
    </div>
</div>