<div id="fundo-externo">
    <div id="fundo">
        <img src="<?php echo $this->baseUrl('img/soccer_fans.jpeg'); ?>" alt="" />
    </div>
</div>
<div class="container">    
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3 text-center">
            <div id="site">
                <h1>SOCCEX</h1>
                <h3>A Rede Social da Torcida Brasileira</h3>
            </div>
        </div>
    </div>    
    <div class="row">
        <div class="col-lg-6">
            <div id="site">
                
            </div>
        </div>
        <div class="col-lg-6">
            <div id="site">
                
            </div>
        </div>
    </div>    
</div>
