<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">                
                <div class="row">
                    <a href="<?php echo $this->url(array(
                        'module' => 'perfil',
                        'controller' => 'page',
                        'action' => 'index'
                    ), 'default', true); ?>">
                        <div class="col-lg-12">
                            <img src="<?php echo $this->baseUrl('views/img/perfil/user_default.png'); ?>" class="img img-circle center-block" />
                        </div>     
                        <div class="col-lg-12 text-center"><h3>Fernando Rodrigues</h3></div>
                    </a>
                </div>    
            </div>
        </div>
    </div>
</div>