<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">                
                <div class="row">
                    <a href="<?php echo $this->url(array(
                        'module' => 'perfil',
                        'controller' => 'page',
                        'action' => 'index'
                    ), 'default', true); ?>">
                        <div class="col-lg-3">
                            <img src="<?php echo $this->baseUrl('views/img/perfil/user_default.png'); ?>" class="img-responsive img-circle"/>                            
                        </div>
                        <div class="col-lg-9">
                            <h4>Fernando Rodrigues</h4>
                        </div>     
                    </a>
                </div>    
                <div class="row">
                    <div class="col-lg-3">
                        <img src="<?php echo $this->baseUrl('views/img/times/cruzeiro.png'); ?>" class="img-responsive img-circle"/>                            
                    </div>
                    <div class="col-lg-9">
                        <h5>Torcedor do Cruzeiro</h5>
                    </div>                    
                </div>    
            </div>
        </div>
    </div>
</div>