<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <img src="<?php echo $this->baseUrl('views/img/times/cruzeiro.png'); ?>" class="img img-circle pull-left" style="margin-right: 10px; width: 40px;" />
                <h4>Cruzeiro</h4>
            </div>
            <div class="panel-body">                
                <div class="row">
                    <div class="col-lg-12">
                        <h5>Confiança da Torcida</h5><hr />
                        <p class="text-muted small">26 avaliações</p>
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                                60%
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <h5>Último Jogo</h5><hr />
                    </div>                    
                </div>                    
                <div class="row text-center">
                    <div class="col-lg-12 text-center small text-muted">05/06/2016 18:30h - Mineirão</div>                        
                </div>
                <div class="row text-center">                    
                    <div class="col-lg-3">
                        <img src="<?php echo $this->baseUrl('views/img/times/cruzeiro.png'); ?>" class="img img-thumbnail center-block" style="margin-right: 10px; width: 40px;" />
                    </div>
                    <div class="col-lg-2">0</div>
                    <div class="col-lg-2">X</div>
                    <div class="col-lg-2">1</div>
                    <div class="col-lg-3">
                        <img src="<?php echo $this->baseUrl('views/img/times/sao_paulo.png'); ?>" class="img img-thumbnail center-block" style="margin-right: 10px; width: 40px;" />
                    </div>                    
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <h5>Próximo Jogo</h5><hr />
                    </div>
                </div> 
                <div class="row text-center">
                    <div class="col-lg-12 text-center small text-muted">12/06/2016 16:00h - Independência</div>                        
                </div>
                <div class="row text-center">                    
                    <div class="col-lg-3">
                        <img src="<?php echo $this->baseUrl('views/img/times/atletico_mg.png'); ?>" class="img img-thumbnail center-block" style="margin-right: 10px; width: 40px;" />
                    </div>                    
                    <div class="col-lg-6">X</div>                    
                    <div class="col-lg-3">
                        <img src="<?php echo $this->baseUrl('views/img/times/cruzeiro.png'); ?>" class="img img-thumbnail center-block" style="margin-right: 10px; width: 40px;" />
                    </div>                    
                </div>
            </div>
        </div>
    </div>
</div>