<div id="fundo-externo">
    <div id="fundo"></div>
</div>
<div class="container">    
    <div class="row">
        <div class="col-lg-12" style="color: #FFF">
            <h1>LOGO</h1>            
        </div>
    </div>    
    <div class="row">
        <div class="col-lg-6">
            <div class="site" id="box-info">
                <p class="bolder">Chegou a rede social para os amantes do futebol!</p>
                <p>
                    O Soccex é uma plataforma para você que gosta do futebol, não 
                    perder a oportunidade de zoar seu amigo quando o time dele
                    perde e adora dar "pitacos" nos jogos da rodada.
                </p>
                <p class="bolder">
                    Faça seu cadastro! Em breve muitas novidades!
                </p>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="site" id="box-cadastro">
                <?php echo $this->messages; ?> 
                <form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" enctype="application/x-www-form-urlencoded">
                    <div class="row"> 
                        <div class="">
                            <div class="form-group">                            
                                
                                <!-- time_id -->
                                <div class="col-xs-12">
                                    <?php echo $this->form->time_id; ?>
                                </div>
                                
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist">
                                  <li role="presentation" class="active">
                                      <a href="#serie-a" aria-controls="home" role="tab" data-toggle="tab">Série A</a>
                                  </li>
                                  <li role="presentation">
                                      <a href="#serie-b" aria-controls="profile" role="tab" data-toggle="tab">Série B</a>
                                  </li>
                                  
                                </ul>
                                
                                <!-- Tab panes -->
                                <div class="tab-content box-times">
                                    <div role="tabpanel" class="tab-pane active" id="serie-a">
                                        <?php foreach ($this->times(1) as $time) : ?>
                                        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6" id="<?php echo $time->time_id; ?>">
                                            <img alt="<?php echo $time->time_nome; ?>" src="<?php echo $this->baseUrl("views/img/times/" . $time->time_escudo); ?>" class="img-responsive img-radio center-block">
                                            <button type="button" class="btn btn-sm btn-primary btn-radio" id="btn-<?php echo $time->time_id; ?>">Escolher</button>           
                                            <input type="checkbox" id="chk-<?php echo $time->time_id; ?>" class="hidden">
                                        </div>
                                        <?php endforeach; ?>
                                    </div>
                                    <div role="tabpanel" class="tab-pane" id="serie-b">
                                        <?php foreach ($this->times(2) as $time) : ?>
                                        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6" id="<?php echo $time->time_id; ?>">
                                            <img alt="<?php echo $time->time_nome; ?>" src="<?php echo $this->baseUrl("views/img/times/" . $time->time_escudo); ?>" class="img-responsive img-radio center-block">
                                            <button type="button" class="btn btn-sm btn-primary btn-radio" id="btn-<?php echo $time->time_id; ?>">Escolher</button>           
                                            <input type="checkbox" id="chk-<?php echo $time->time_id; ?>" class="hidden">
                                        </div>
                                        <?php endforeach; ?>
                                    </div>                                    
                                </div>
                            </div>        
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-xs-12">
                                <?php echo $this->form->perfil_email; ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <?php echo $this->form->submit; ?>                                                        
                        </div>
                    </div>                    
                </form>
            </div>
        </div>
    </div>  
    <div class="row">
        <div class="col-lg-12 text-center">
            <div class="site">
                <p>Curta nossa redes sociais</p>
                <p>
                    <a href="" class="redes-sociais"><i class="fa fa-facebook-square fa-4x"></i></a>
                    <a href="" class="redes-sociais"><i class="fa fa-twitter-square fa-4x"></i></a>
                </p>
            </div>
        </div>
    </div>
</div>
