<?php echo $this->doctype(); ?>

<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Soccex</title>

        <!-- CSS -->
        <link href="<?php echo $this->baseUrl("views/css/bootstrap.min.css"); ?>" rel="stylesheet">        
        <link href="<?php echo $this->baseUrl("views/css/bootstrap-theme.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/font-awesome.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/style.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/perfil/style.css"); ?>" rel="stylesheet">

        <!-- Js -->
        <script src="<?php echo $this->baseUrl("views/js/jquery.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/bootstrap.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/application.js"); ?>"></script>
        
        <?php echo $this->headScript(); ?>
        
    </head>
    <body>
        <?php echo $this->messages; ?>
        <?php echo $this->partial('partials/perfil/menu.phtml'); ?>
        <div class="container" id="content">            
            <div class="row">
                <div class="col-lg-3">
                    <!-- PERFIL -->
                    <?php echo $this->partial('partials/perfil/left-bar-perfil.phtml'); ?>
                </div>
                <div class="col-lg-6">
                    <!-- CONTENT -->
                    <?php echo $this->layout()->content; ?>
                </div>
                <div class="col-lg-3">
                    <!-- SOBRE DO SEU TIME -->
                    <?php echo $this->partial('partials/perfil/left-bar-time.phtml'); ?>
                </div>
            </div>            
        </div> <!-- /container -->        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
