<div class="container">    
    <div class="row">
        <div class="col-lg-12">
            <h3>Times</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 text-right">
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'time',
                'action' => 'cadastro'
            ), 'default', true); ?>" class="btn btn-sm btn-success">
                <i class="fa fa-plus"></i> Novo Time
            </a>
        </div>
    </div>
</div>